from tkinter import *
from tkinter import messagebox
import mysql.connector
mb=mysql.connector.connect(
    host="Localhost",
    user="root",
    password="P@ndu1818",
    database='PYTHON_PROJECT'
    )
root=Tk()
#Images Used  
img1=PhotoImage(file='C:\\python\\mylogo.png')
img2=PhotoImage(file='C:\\python\\images.png')
img3=PhotoImage(file='C:\\python\\Untitledo.png')
img4=PhotoImage(file='C:\\python\\Untitled.png')
img5=PhotoImage(file='C:\\python\\Untitledo9.png')
img6=PhotoImage(file='C:\\python\\park.png')
img7=PhotoImage(file='C:\\python\\park21.png')
img8=PhotoImage(file='C:\\python\\park2156.png')
img9=PhotoImage(file='C:\\python\\Untitled876.png')
img10=PhotoImage(file='C:\\python\\login.png')
#Main Manu Window
def openMM():
    top=Toplevel()
    top.title('Main Menu')
    top.geometry('330x600+660+30')
    f=Canvas(top,width=330,height=600,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    f.pack()
    f.create_image(10,40,image=img1,anchor=W)
    Label(top,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    Button(top,text='Contact Us',width=31,height=2,bg='lightblue4',fg='grey99',activebackground='lightcyan4',command=openCU,bd=3,relief=RAISED).place(x=90,y=420)
    Button(top,text='Parking Slot',width=31,height=2,bg='lightblue4',fg='grey99',activebackground='lightcyan4',bd=3,relief=RAISED,command=openSB).place(x=10,y=120)
    Button(top,text='Change Password',width=31,height=2,bg='lightblue4',fg='grey99',activebackground='lightcyan4',bd=3,command=changePWD,relief=RAISED).place(x=90,y=220)
    Button(top,text='Feedback',width=31,height=2,bg='lightblue4',fg='grey99',activebackground='lightcyan4',bd=3,command=fb,relief=RAISED).place(x=10,y=320)
    Button(top,text='Back',height=1,width=10,bg='lightblue4',fg='grey99',activebackground='lightcyan4',command=top.destroy,bd=3).place(x=230,y=550)
    top.mainloop()
#Slot Booking Window    
def openSB():
    top0=Toplevel()
    top0.title('Slot Booking')
    top0.geometry('920x700+330+30')
    f=Canvas(top0,width=920,height=700,bg='lightblue4',highlightbackground='lightcyan4',highlightthickness='10')
    f.pack()
    img1=PhotoImage(file='C:\\python\\mylogo.png')
    email=StringVar()
    Phn=IntVar()
    date=StringVar()
    time=IntVar()
    Label(top0,text='E-mail            : ',bg='lightblue4',fg='white',font=('Impact',15)).place(x=20,y=130)
    Entry(top0,width=25,bd=3,font=('JavaneseText'),bg='grey90',textvariable=email).place(x=130,y=130)
    Label(top0,text='Phone No     : ',bg='lightblue4',fg='white',font=('Impact',15)).place(x=20,y=235)
    Entry(top0,width=25,bd=3,font=('JavaneseText'),bg='grey90',textvariable=Phn).place(x=130,y=240)
    Label(top0,text='Address        : ',bg='lightblue4',fg='white',font=('Impact',15)).place(x=20,y=340)
    tb=Text(top0,width=22,height=5,bg='grey90',fg='black',font=('JavaneseText'),padx=20,pady=20)
    tb.place(x=130,y=345)
    Label(top0,text='Date : ',bg='lightblue4',fg='white',font=('Impact',15)).place(x=20,y=520)
    Entry(top0,width=10,bd=3,font=('JavaneseText'),bg='grey90',textvariable=date).place(x=130,y=525)
    Label(top0,text='Time : ',bg='lightblue4',fg='white',font=('Impact',15)).place(x=250,y=520)
    Spinbox(top0,from_=1,to=24,width=10,bg='grey90',textvariable=time).place(x=320,y=530)
    mycursor=mb.cursor() 
    v1=IntVar()
    variable=1
    def slot(value):
        global variable
        variable=value
        mycursor.execute("update SignUp set Phone_No=%s,Address=%s,Date=%s,time=%s,slot=%s where Email_id=%s",(Phn.get(),tb.get("1.0","end-1c"),date.get(),time.get(),variable,email.get()))
        mb.commit()    
    def display():
        mycursor.execute("select * from SignUp")
        x=mycursor.fetchall()
        for i in x:
            print(i)
    def fun2():
        messagebox.showinfo("Thanks","Your Slot has been booked")
    Label(top0,text='      Select Your Slot',bg='white',fg='black',font=('bold')).place(x=600,y=40)
    f.create_line(675,0,675,700,fill='white',width=500)            
    b1=Button(top0,text='SLOT 1',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 1'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b1.place(x=450,y=100)
    b2=Button(top0,text='SLOT 2',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 2'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b2.place(x=750,y=100)
    b3=Button(top0,text='SLOT 3',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 3'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b3.place(x=450,y=220)
    b4=Button(top0,text='SLOT 4',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 4'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b4.place(x=750,y=220)
    b5=Button(top0,text='SLOT 5',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 5'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b5.place(x=450,y=340)
    b6=Button(top0,text='SLOT 6',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 6'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b6.place(x=750,y=340)
    b7=Button(top0,text='SLOT 7',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 7'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b7.place(x=450,y=460)
    b8=Button(top0,text='SLOT 8',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 8'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b8.place(x=750,y=460)
    b9=Button(top0,text='SLOT 9',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 9'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b9.place(x=450,y=580)
    b10=Button(top0,text='SLOT 10',height=5,width=20,bg='lightblue4',fg='grey99',command=lambda:[slot('Slot 10'),display(),fun2()],activebackground='lemon chiffon',bd=3)
    b10.place(x=750,y=580)
    f.create_image(840,50,image=img1,anchor=W)
    top0.mainloop()
#Change Passwoed Window  
def changePWD():
    top1=Toplevel()
    top1.title('Change Password')
    top1.geometry('600x370')
    g=Canvas(top1,width=600,height=370,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    g.pack()
    g.create_image(10,40,image=img1,anchor=W)
    pwd=StringVar()
    email=StringVar()
    Label(top1,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top1,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    Label(top1,text='Enter E-Mail ID                      : ',bg='white',font=('Impact')).place(x=70,y=120)
    Entry(top1,width=25,bd=3,font=('JavaneseText'),bg='lightblue4',fg='white',textvariable=email).place(x=300,y=125)
    Label(top1,text='Enter New Password           : ',bg='white',font=('Impact')).place(x=70,y=200)
    Entry(top1,width=25,bd=3,font=('JavaneseText'),bg='lightblue4',fg='white',textvariable=pwd,show='*').place(x=300,y=205)
    mycursor=mb.cursor()
    def update():
        mycursor.execute('update SignUp set password=%s where Email_id=%s',(pwd.get(),email.get()))
        mb.commit()
    def display():
        mycursor.execute("select * from SignUp")
        x=mycursor.fetchall()
        for i in x:
            print(i)
    Button(top1,text='Change Password',width=39,bg='lightblue4',fg='white',activebackground='lightcyan4',command=lambda:[update(),display()],relief=GROOVE).place(x=300,y=280)
    Button(top1,text='Back',height=1,width=10,bg='lightblue4',fg='white',activebackground='lightcyan4',command=top1.destroy,bd=3).place(x=490,y=320)
    top1.mainloop()
def fun1():
    messagebox.showinfo("Thanks","Thank you for the feedback")
#Feedback Window    
def fb():
    top2=Toplevel()
    top2.title('Feedback')
    top2.geometry('600x480')
    h=Canvas(top2,width=600,height=480,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    h.pack()
    h.create_image(10,40,image=img1,anchor=W)
    Label(top2,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top2,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    mycursor=mb.cursor()
    def update():
        mycursor.execute('update SignUp set feedback=%s where Email_id=%s',(textBox.get("1.0","end-1c"),email.get()))
        mb.commit()
    def display():
        mycursor.execute("select * from SignUp")
        x=mycursor.fetchall()
        for i in x:
            print(i)
    email=StringVar()
    Label(top2,text='Email       : ',bg='white',font=('SegoePrint')).place(x=30,y=110)
    Entry(top2,width=37,bd=3,font=('JavaneseText'),bg='lightblue4',fg='white',textvariable=email).place(x=150,y=110)    
    textBox=Text(top2,width=45,height=7,bg='lightblue4',fg='white',font=('JavaneseText'),padx=20,pady=20)
    textBox.place(x=30,y=170)
    Label(top2,text='Feedback    ',bg='white',font=('SegoePrint')).place(x=30,y=140)
    Button(top2,text='Submit',width=75,bg='lightblue4',fg='grey99',activebackground='lightcyan4',command=lambda:[update(),display(),fun1()],relief=GROOVE).place(x=30,y=390)
    Button(top2,text='Back',height=1,width=10,bg='lightblue4',fg='grey99',activebackground='lightcyan4',command=top2.destroy,bd=3).place(x=480,y=430)
    top2.mainloop()
#Contact Us Window    
def openCU():
    top3=Toplevel()
    top3.title('CONTACT US')
    top3.geometry('800x750+700+20')
    d=Canvas(top3,width=800,height=800,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    d.pack()
    d.create_image(10,40,image=img1,anchor=W)
    d.create_image(550,10,image=img2,anchor=NW)
    Label(top3,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top3,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    Label(top3,text='               Gmail:',width=17,height=2,font=('bold'),bg='white',fg='red').place(x=250,y=150)
    Label(top3,text='\n       vamsi292001@gmail.com',height=2,font=('bold'),bg='white',fg='snow4').place(x=250,y=200)
    Label(top3,text='\n  veerapandu2372001@gmail.com',height=2,font=('bold'),bg='white',fg='snow4').place(x=250,y=250)
    Label(top3,text='\nprahalladhraju26072002@gmail.com',height=2,font=('bold'),bg='white',fg='snow4').place(x=250,y=300)
    Label(top3,text='\n    WhatsApp Numbers:',font=('bold'),bg='white',fg='red').place(x=280,y=400)
    Label(top3,text='\n      8328215129',height=2,font=('bold'),bg='white',fg='snow4').place(x=300,y=450)
    Label(top3,text='\n      8074631215',height=2,font=('bold'),bg='white',fg='snow4').place(x=300,y=500)
    Label(top3,text='\n      8096563070',height=2,font=('bold'),bg='white',fg='snow4').place(x=300,y=550)
    Label(top3,text='T',bg='dark slate grey',fg='salmon',width=10,height=9).place(x=30,y=600)
    Label(top3,text='H',bg='dark slate grey',fg='orange',width=10,height=6).place(x=130,y=645)
    Label(top3,text='A',bg='dark slate grey',fg='hot pink',width=10,height=3).place(x=225,y=690)
    Label(top3,text='N',bg='dark slate grey',fg='yellow',width=10,height=1).place(x=320,y=720)
    Label(top3,text='K',bg='dark slate grey',fg='deepskyblue2',width=10,height=1).place(x=415,y=720)
    Label(top3,text='Y',bg='dark slate grey',fg='aquamarine',width=10,height=3).place(x=510,y=690)
    Label(top3,text='O',bg='dark slate grey',fg='cyan',width=10,height=6).place(x=600,y=645)
    Label(top3,text='U _/ \_',bg='dark slate grey',fg='tan1',width=10,height=9).place(x=695,y=600)  
    top3.mainloop()
#Login Window
def fun2():
    messagebox.showinfo("Warning","Invalid User Details")
def openLG():
    top4=Toplevel()
    top4.title('Login')
    mycursor=mb.cursor()
    top4.geometry('800x750+700+20')
    b=Canvas(top4,width=800,height=750,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    b.pack()
    b.create_image(10,40,image=img1,anchor=W)
    b.create_image(500,100,image=img10)
    Label(top4,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top4,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    user=StringVar()
    pwd=StringVar()
    Label(top4,text='User Name    : ',bg='white',font=('Impact',15)).place(x=240,y=200)
    Entry(top4,textvariable=user,width=25,bd=3,font=('JavaneseText'),bg='grey90').place(x=390,y=205)
    Label(top4,text='Password      : ',bg='white',font=('Impact',15)).place(x=240,y=300)
    Entry(top4,textvariable=pwd,width=25,bd=3,font=('JavaneseText'),bg='grey90',show='*').place(x=390,y=300)
    def savedata():
        mycursor.execute('select * from SignUp where username=%s and password=%s',(user.get(),pwd.get()))
        x=mycursor.fetchall()
        for i in x:
            openMM()
            break
        else:
            fun2()
    Button(top4,text='Login',width=39,bg='slate grey',fg='grey99',bd=3,activebackground='lightcyan4',command=savedata,relief=RAISED).place(x=390,y=380)   
    Button(top4,text='Back',height=1,width=10,bg='slate grey',fg='grey99',activebackground='lightcyan4',command=top4.destroy,bd=3).place(x=700,y=690) 
    Label(top4,text='     W',bg='dark slate grey',fg='white',width=34,height=3).place(x=10,y=100)
    Label(top4,text='E',bg='dark slate grey',fg='white',width=15,height=3).place(x=10,y=160)
    Label(top4,text=' L',bg='dark slate grey',fg='white',width=23,height=3).place(x=10,y=220)
    Label(top4,text='C',bg='dark slate grey',fg='white',width=31,height=3).place(x=10,y=280)
    Label(top4,text='O',bg='dark slate grey',fg='white',width=15,height=3).place(x=10,y=340)
    Label(top4,text='                     M',bg='dark slate grey',fg='white',width=35,height=3).place(x=10,y=400)
    Label(top4,text='E',bg='dark slate grey',fg='white',width=28,height=3).place(x=10,y=460)
    Label(top4,text='',bg='dark slate grey',fg='white',width=18,height=3).place(x=10,y=520)
    Label(top4,text=':)',bg='dark slate grey',fg='white',width=37,height=3).place(x=10,y=580)
    Label(top4,text='',bg='dark slate grey',fg='white',width=28,height=3).place(x=10,y=640)
    top4.mainloop()
#SignUp Window
def openSU():
    top5=Toplevel()
    top5.title('SignUp')
    top5.geometry('800x750+700+20')
    mycursor=mb.cursor()
    #mycursor.execute("create table SignUp(username VARCHAR(30),Email_id VARCHAR(30),password VARCHAR(10),Phone_No int,Address VARCHAR(100),date VARCHAR(20),Time int,Slot VARCHAR(10),feedback VARCHAR(300))")
    b=Canvas(top5,width=800,height=750,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    b.pack()
    b.create_image(10,40,image=img1,anchor=W)
    Label(top5,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top5,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    user=StringVar()
    pwd=StringVar()
    email=StringVar()
    Label(top5,text='User Name : ',bg='white',font=('Impact',15)).place(x=340,y=220)
    Entry(top5,textvariable=user,width=25,bd=3,font=('JavaneseText'),bg='grey90').place(x=490,y=225)
    Label(top5,text='E-Mail ID      : ',bg='white',font=('Impact',15)).place(x=340,y=320)
    Entry(top5,textvariable=email,width=25,bd=3,font=('JavaneseText'),bg='grey90').place(x=490,y=320)
    Label(top5,text='Password    : ',bg='white',font=('Impact',15)).place(x=340,y=420)
    Entry(top5,textvariable=pwd,width=25,bd=3,font=('JavaneseText'),bg='grey90',show='*').place(x=490,y=425)
    b.create_line(300,200,300,600,fill='black',width=1)
    def savedata():
        mycursor.execute('insert into SignUp values(%s,%s,%s,NULL,NULL,NULL,NULL,NULL,NULL)',(user.get(),email.get(),pwd.get()))
        mb.commit()
    def display():
        mycursor.execute("select * from SignUp")
        x=mycursor.fetchall()
        for i in x:
            print(i)
    Button(top5,text='Join Parking Click!',width=39,bd=3,bg='slate grey',fg='grey99',activebackground='lightcyan4',command=lambda:[savedata(),display(),openMM()],relief=RAISED).place(x=490,y=500)
    Button(top5,text='Back',height=1,width=10,bg='slate grey',fg='grey99',activebackground='lightcyan4',command=top5.destroy,bd=3).place(x=700,y=690)
    Label(top5,text='PARKING\nCLICK',fg='white',font=('Impact',20,'bold'),bg='dark slate grey',width=15,height=6).place(x=50,y=260)
    Label(top5,text='',bg='dark slate grey',width=12,height=9).place(x=700,y=10)
    Label(top5,text='',bg='dark slate grey',width=12,height=6).place(x=600,y=10)
    Label(top5,text='',bg='dark slate grey',width=12,height=3).place(x=500,y=10)
    Label(top5,text='',bg='dark slate grey',width=12,height=1).place(x=400,y=10)
    Label(top5,text='',bg='dark slate grey',width=12,height=9).place(x=10,y=600)
    Label(top5,text='',bg='dark slate grey',width=12,height=6).place(x=110,y=645)
    Label(top5,text='',bg='dark slate grey',width=12,height=3).place(x=210,y=690)
    Label(top5,text='',bg='dark slate grey',width=12,height=1).place(x=310,y=720)
    top5.mainloop()
#AboutUs window
def openAU():
    top=Toplevel()
    top.title('AboutUs')
    top.geometry('800x750+700+20')
    d=Canvas(top,width=800,height=750,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
    d.pack()
    d.create_image(40,45,image=img1)
    d.create_image(550,10,image=img2,anchor=NW)
    Label(top,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='snow4').place(x=61,y=10)
    Label(top,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=80,y=46)
    Label(top,text='About Us',width=10,bg='white',font=('bold',15)).place(x=330,y=80)
    Label(top,text='The main things one should know about our\n\n     services are that we are providing THE BEST\n\n',bg='white',font=('bold')).place(x=80,y=140)
    Label(top,text='    SECURITY for your   vehicle by providing CC CAM monitoring\n\n          service and GOOD MAINTENANCE of the vehicles and we have \n\nGOOD SPACE for PARKING . We are providing you 24x7\n\n SERVICE.',bg='white',font=('bold')).place(x=50,y=230)
    Label(top,text='\n                               Other Services',bg='white',font=('bold',15)).place(x=160,y=430)
    Label(top,text='\n\n                        Tunnel Wash , Automatic In-Bay Car Wash , Hand Wash \n\n                       Waterless Wash.',bg='white',font=('bold')).place(x=10,y=480)
    Label(top,text='T',bg='dark slate grey',fg='salmon',width=10,height=9).place(x=30,y=600)
    Label(top,text='H',bg='dark slate grey',fg='orange',width=10,height=6).place(x=130,y=645)
    Label(top,text='A',bg='dark slate grey',fg='hot pink',width=10,height=3).place(x=225,y=690)
    Label(top,text='N',bg='dark slate grey',fg='yellow',width=10,height=1).place(x=320,y=720)
    Label(top,text='K',bg='dark slate grey',fg='deepskyblue2',width=10,height=1).place(x=415,y=720)
    Label(top,text='Y',bg='dark slate grey',fg='aquamarine',width=10,height=3).place(x=510,y=690)
    Label(top,text='O',bg='dark slate grey',fg='cyan',width=10,height=6).place(x=600,y=645)
    Label(top,text='U _/ \_',bg='dark slate grey',fg='tan1',width=10,height=9).place(x=695,y=600)
    top.mainloop()
root.geometry('800x750+700+20')
root.title('PARKING MANAGEMENT SYSTEM')
c=Canvas(width=800,height=750,bg='white',highlightbackground='lightcyan4',highlightthickness='10')
c.pack()
Label(root,text='PARKING CLICK',width=17,heigh=2,font=('Impact'),bg='white',fg='slate grey').place(x=61,y=10)
Label(root,text='  We Make Your Life Easier : )',font=('Gabriola'),bg='white',fg='slate grey').place(x=80,y=46)
Label(root,text='Contact Us : 77788881099\n                           9988222298',font=('Gabriola'),bg='white',fg='dark slate grey').place(x=620,y=650)
b1=Button(root,text="Login",bg='slate grey',fg='grey99',width=15,height=2,activebackground='lightcyan4',font=('bold'),bd=2,relief=RAISED,cursor='star',command=openLG)
b1.place(x=440,y=10)
b2=Button(root,text="SignUp",bg='slate grey',fg='grey99',width=15,height=2,activebackground='lightcyan4',font=('bold'),bd=2,relief=RAISED,cursor='star',command=openSU)
b2.place(x=265,y=10)
b3=Button(root,text="About Us",bg='slate grey',fg='grey99',width=15,height=2,activebackground='lightcyan4',font=('bold'),bd=2,relief=RAISED,cursor='star',command=openAU)
b3.place(x=615,y=10)
c.create_image(10,40,image=img1,anchor=W)
c.create_image(80,280,image=img3,anchor=W)
c.create_image(400,400,image=img4)
c.create_image(400,170,image=img5)
c.create_image(500,180,image=img6,anchor=NW)
c.create_image(520,380,image=img7,anchor=NW)
c.create_image(190,600,image=img8,anchor=S)
c.create_image(300,520,image=img9,anchor=NW)
Label(root,text='',bg='dark slate grey',width=10,height=3).place(x=10,y=500)
Label(root,text='',bg='dark slate grey',width=15,height=3).place(x=10,y=560)
Label(root,text='',bg='dark slate grey',width=20,height=3).place(x=10,y=620)
Label(root,text='',bg='dark slate grey',width=25,height=3).place(x=10,y=680)
root.mainloop()
